name = "questionnaire-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
DATABASE_URL = "postgres://user:password@host:port/database"

[[d1_databases]]
binding = "DB"
database_name = "questionnaire_db"
database_id = "xxx" 