name = "questionnaire-api"
main = "src/index.js"
compatibility_date = "2024-05-19"
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL = "postgresql://postgres:bXBcKw2wWybAXDtE@150.109.112.155:5432/question_db"

[env.development]
vars = { DATABASE_URL = "postgres://pguser:123456@localhost:5432/honostudy" }

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



