name = "questionnaire-api"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 移除自定义构建步骤，让 Wrangler 处理
# [build]
# command = "npx esbuild src/index.js --bundle --outfile=dist/index.js --platform=node --format=esm --external:pg-native --external:pg --external:tedious --external:sqlite3 --external:mysql2 --external:oracledb --external:better-sqlite3 --external:hono --external:@hono/node-server --external:hono/cors --external:yaml --external:dotenv --external:drizzle-orm --external:drizzle-orm/postgres-js --external:drizzle-orm/pg-core --external:postgres"

# 添加 esbuild 特定配置
[build.esbuild]
format = "esm"
bundle = true
minify = true
sourcemap = true

[env.production]

[vars]
DATABASE_URL = "postgresql://stock-question_owner:npg_OqrNj3SDlH2M@ep-withered-resonance-a46siw1o-pooler.us-east-1.aws.neon.tech/stock-question?sslmode=require"

